cms_system/cms_system/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),

    path('admin/', admin.site.urls),

    path('polls/', include('polls.urls')),
    path('user/', include('user.urls')),
    path('contents/', include('contents.urls')),
    path('display/', include('display.urls')),

    # 김보
    path('community/', include('community.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cms_system/display/urls.py
from django.urls import path
from . import views

app_name = "display"

urlpatterns = [
    path('', views.just, name='just'),
    path('signage/', views.signageView, name='signage'),
    path('picture/<int:id>', views.picDetail, name="picture"),
    path('media/<int:id>', views.mediDetail, name="media"),
    path('ContentLike/<int:id>', views.ContentLike, name="ContentLike"),
    path('VODLike/<int:id>', views.VODLike, name="VODLike")
]

cms_system/user/urls.py
#-*- coding: utf-8 -*-

from . import views
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.just, name='just'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
]

cms_system/display/models.py
from django.db import models

# Create your models here.

cms_system/display/views.py
from django.shortcuts import render, redirect, reverse
from contents.models import Contents, Contents_Description, Theme
import json
from django.core.serializers.json import DjangoJSONEncoder
from user.models import CustomUser
from django.http import HttpResponseRedirect
def just(request):
    print("just")

    return render(request, 'display/just.html')

def signageView(request):

    img_list = Contents.objects.filter(contentType='IMG')
    vod_list = Contents.objects.filter(contentType='VOD')
    thumbnail_list = Contents_Description.objects.exclude(thumbnailPath=None).values('thumbnailPath')

    # print("img", img_list)
    # print("vod", vod_list)
    # print("thumbnail_list", thumbnail_list)

    for idx, img in enumerate(img_list):

        usernickname = CustomUser.objects.get(user_id=img.userFK_id)
        img.nickname = usernickname.nickname

    for idx, vod in enumerate(vod_list):
        # print("vod {0}".format(vod))
        vod.thumbnail = thumbnail_list[idx]['thumbnailPath']
        usernickname = CustomUser.objects.get(user_id=vod.userFK_id)
        vod.nickname = usernickname.nickname

    context = {
        "img_list": img_list,
        "vod_list": vod_list,
    }

    return render(request, 'display/signageShow.html', context)

def picDetail(request, id):

    contents = Contents.objects.get(id=id)
    cont_user_id = Contents.objects.filter(id=id).values("userFK")
    description_user = CustomUser.objects.filter(user__in=cont_user_id).values('user_description')
    user_img = CustomUser.objects.filter(user__in=cont_user_id).values('user_profile')
    description = Contents_Description.objects.get(contentFK=contents)
    theme_list = Theme.objects.all()


    c = Contents.objects.filter(id=id).values("theme_id")
    contents_in_theme = Theme.objects.get(id__in=c)
    contents_in_themeValue = contents_in_theme.themeValue

    nickname = CustomUser.objects.get(user_id=contents.userFK_id)
    contents.nickname = nickname
    contents.hits += 1

    contents.save()

    content2server = list(Contents.objects.filter(id=id).values('id', 'title', 'upload_file'))

    context = {
        "contents_info": contents,
        "description_info": description,
        'theme_list': theme_list,
        'contents_in_themeValue': contents_in_themeValue,
        'description_user': description_user,
        'content2server': content2server,
        'user_img': user_img,
        # 'user_list': user_list,
    }

    return render(request, 'display/picdetail.html', context)

def mediDetail(request, id):

    print("media page")

    contents = Contents.objects.get(id=id)
    cont_user_id = Contents.objects.filter(id=id).values("userFK")
    description_user = CustomUser.objects.filter(user__in=cont_user_id).values('user_description')
    user_img = CustomUser.objects.filter(user__in=cont_user_id).values('user_profile')
    description = Contents_Description.objects.get(contentFK=contents)
    theme_list = Theme.objects.all()

    c = Contents.objects.filter(id=id).values("theme_id")
    contents_in_theme = Theme.objects.get(id__in=c)
    contents_in_themeValue = contents_in_theme.themeValue

    nickname = CustomUser.objects.get(user_id=contents.userFK_id)
    contents.nickname = nickname
    contents.hits += 1

    contents.save()

    content2server = list(Contents.objects.filter(id=id).values('id', 'title', 'upload_file'))
    # print("content2server", content2server)

    context = {
        "contents_info": contents,
        "description_info": description,
        'theme_list': theme_list,
        'contents_in_themeValue': contents_in_themeValue,
        'description_user': description_user,
        'content2server': content2server,
        'user_img': user_img,
        # 'user_list': user_list,
    }

    return render(request, 'display/mediadetail.html', context)

def ContentLike(request, id):
    print("contents like")

    contents = Contents.objects.get(id=id)

    contents.likes += 1
    contents.save()

    return redirect('display:picture', contents.id)

def VODLike(request, id):
    print("VODLike ")

    contents = Contents.objects.get(id=id)

    contents.likes += 1
    contents.save()

    return redirect('display:media', contents.id)

cms_system/display/templates/display/backupshow.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <style>
            a {
                color: #42b983;
            }
            ul {
                text-align: center;
            }
            .w3-center {
                display: flex;
                justify-content: center;
                align-items: center;
            }

            .container div {
              width: 250px;
              background-color: antiquewhite;
              display: flex;
              justify-content: center;
              align-items: center;
              border-radius: 1rem;
            }

              .container img {
              width: 100%;
              }

            /* The Modal (background) */
            .modal {
              display: none; /* Hidden by default */
              position: fixed; /* Stay in place */
              z-index: 1; /* Sit on top */

              left: 0;
              top: 0;
              width: 100%; /* Full width */
              height: 100%; /* Full height */
              overflow: auto; /* Enable scroll if needed */
              background-color: rgb(0,0,0); /* Fallback color */
              background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
            }

            /* Modal Content */
            .modal-content {
              background-color: #fefefe;
              margin: auto;
              padding: 20px;
              border: 1px solid #888;
              width: 90%;
                height: 100%;
            }

            /* The Close Button */
            .close {
              color: #aaaaaa;
              float: right;
              font-size: 28px;
              font-weight: bold;
            }

            .close:hover,
            .close:focus {
              color: #000;
              text-decoration: none;
              cursor: pointer;
            }

        </style>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.1.2/fullpage.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.9/fullpage.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.1.2/vendors/easings.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.1.2/vendors/easings.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.1.2/vendors/scrolloverflow.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.1.2/vendors/scrolloverflow.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.1.2/vendors/scrolloverflow.min.js.map"></script>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.1.2/fullpage.css" />
        <link rel="stylesheet" type="text/css" href="https://www.w3schools.com/w3css/4/w3.css" />
    </head>

    <body>
        <div id="fullpage">
            <div class="section">
                <div class="slide">
                    <div class="container">
                     {% for content in img_list %}
                                <div class="w3-quarter">

                                <img src= "/media/{{content.upload_file}}" \
                                     alt="No Content" \
                                     style="width:100%; height:100%; cursor:pointer" \
                                     onclick="showContents(this)" class="w3-hover-opacity contents">
                                </div>
                     {%endfor%}
                    </div>
                </div>
            </div><!-- section -->

            <div class="section">
                <div class="slide">
                    <div class="container">
                     {% for content in vod_list %}

                                <div class="w3-quarter">
                                <video controls>
                                        <source src= "/media/{{content.upload_file}}">
                                    </video>
                                </div>

                     {%endfor%}
                    </div>
                </div>
            </div>

        </div> <!-- fullpage -->

        <!-- The Modal -->
        <div id="c_modal" class="w3-modal" onclick="this.style.display='none'">
          <span class="w3-button w3-hover-red w3-xlarge w3-display-topright">&times;</span>
          <div class="w3-modal-content w3-animate-zoom">
            <img id="cont" style="width:50%">
          </div>
        </div>

<script type="text/javascript">

//자바스크립트에서 템플릿 태그로 그대로 로드할 시 escape 문자와 함께 출력 됨
    //이를 해결하기 위해 템플릿 태그 내 | safe 옵션을 붙이지만 json 형태로 변환할 수 없음
    //대신 .replace(/&#x27;/g, "\""); 통해 escape 문자 삭제 가능

    //현재 json으로 옮기는 도중 모든 객체를 가진 오브젝트는 json으로 변환이 되지 않는 것을 보았다
    //이는 특정 필드가 재대로 변환되지 않는다는 뜻

    //id, title, upload_file
    // var contents_object_val_list_spec = "{{contents_object_val_list_spec}}".replace(/&#x27;/g, "\"");
    //     console.log("contents_object_val_list_spec", contents_object_val_list_spec);
    //
    // const contents_object_val_list_spec_json = JSON.parse(contents_object_val_list_spec);
    //  console.log("contents_object_val_list_spec_json", contents_object_val_list_spec_json);

    //오브젝트 전체
    let rawdata = "{{contents_list_dic}}";
    //console.log("rawdata", rawdata);

    var contents_list_dic = "{{contents_list_dic}}".replace(/&quot;/g, "\"");
        //console.log("contents_list_dic", contents_list_dic);

    const contents_list_json = JSON.parse(contents_list_dic);
    //console.log("contents_list_json", contents_list_json);

    // for(var key in contents_list_json){
    //     console.log("각 객체", contents_list_json[key]);
    //     console.log("id : ", contents_list_json[key]["id"]);
    //     console.log("title : ", contents_list_json[key]["title"]);
    //     console.log("upload_file : ", contents_list_json[key]["upload_file"]);
    //     console.log("contents_list_json 의 키값 : ", Object.keys(contents_list_json));
    // }

//let globalVal = "";

//선택 콘텐츠 정보를 비동기 방식으로 프로젝터 페이지로 전송
    let $pushEvt = $('.contents').on('click', function() {
        let idx = $pushEvt.index(this); // <- 변경된 코드
        console.log(idx);

        if(idx in Object.keys(contents_list_json)){
            // console.log("각 객체", contents_list_json[idx]);
            // console.log("id : ", contents_list_json[idx]["id"]);
            // console.log("title : ", contents_list_json[idx]["title"]);
            // console.log("upload_file : ", contents_list_json[idx]["upload_file"]);

            let contents_data = {
            'id': contents_list_json[idx]["id"],
            'title': contents_list_json[idx]["title"],
            'upload_file': contents_list_json[idx]["upload_file"],
            //다른 요소 추가 가능
            };

            let json_contents_data = JSON.stringify(contents_data)

            let globalVal = contents_list_json[idx]["upload_file"];
            console.log("미디어 서버 전송 데이터", contents_list_json[idx]["upload_file"]);

            webSocket.send(globalVal);
            // 서버로 메시지를 전송하는 함수
        }
    });

    // 선택 콘텐츠 시각화
    function showContents(element) {
          document.getElementById("cont").src = element.src;
          document.getElementById("c_modal").style.display = "block";
    }

// Websocket connection - start
// 웹 서버를 접속한다.
var webSocket = new WebSocket("ws://203.250.33.53:9998");
// 웹 서버와의 통신을 주고 받은 결과를 출력할 오브젝트를 가져옵니다.
var messageTextArea = document.getElementById("messageTextArea");
// 소켓 접속이 되면 호출되는 함수
webSocket.onopen = function(message){
    console.log("Server connect...\n");

};
// 소켓 접속이 끝나면 호출되는 함수
webSocket.onclose = function(message){
    console.log("Server Disconnect...\n");
};
// 소켓 통신 중에 에러가 발생되면 호출되는 함수
webSocket.onerror = function(message){
    console.log("error...\n");
};
// 소켓 서버로 부터 메시지가 오면 호출되는 함수.
webSocket.onmessage = function(message){
// 출력 area에 메시지를 표시한다.
    console.log("Recieve From Server => "+message.data+"\n");
};

//서버 접속 끊
function disconnect(){
webSocket.close();
}
// Websocket connection - end

</script>
        <script src="{% static 'magic_grid/js/magicgrid.js' %}"></script>
    </body>
</html>

cms_system/display/templates/display/base.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

cms_system/display/templates/display/just.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

        <link href="{% static './assets/css/button.css' %}" rel="stylesheet">

</head>
<body>
<div id="btn_group">
    <button id="test_btn1">테스트1</button>
    <button id="test_btn2">테스트2</button>
</div>


</body>
</html>

cms_system/display/templates/display/mediadetail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <link href="{% static './assets/css/detail.css' %}" rel="stylesheet">
        <link href="{% static './assets/css/button.css' %}" rel="stylesheet">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" type="text/css" href="https://www.w3schools.com/w3css/4/w3.css">
    </head>

    <body>
<!--    전체 레이아웃 시작-->
    <div id="wrap">
<!--    헤더-->
    <div class="container">
	 <div class="w3-top" style="margin-left: -80px; right: 0px">
             <div class="w3-bar w3-black w3-card" style="font-size: 30px;">
                 <a href="{% url 'display:signage' %}" \
                    class="w3-bar-item w3-button w3-padding-large" \
                    style="justify-content: center;">BACK</a>

                 <a href="{% url 'index' %}" \
                    class="w3-bar-item w3-button w3-padding-large w3-hide-small" \
                    style="justify-content: center;" >COMMUNITY</a>
             </div>
	</div>

        <article class="no-pd" id="content" > </article>
        <div class="headerBlock"></div>
        <section id="section1" style="margin-top: 69px;">
            <div class="container">
                <p></p>
                <form method="POST" enctype="multipart/form-data"> <!-- 왜 form 태그가 있는거지? -->
                    {% csrf_token %}
                    <div id="div1">
                        <video id="picture" style="height: 400px; width: 100%; object-fit: cover;" autoplay controls loop muted poster="https://cdn.pixabay.com/photo/2020/05/30/17/57/flower-5239814_960_720.jpg" preload="auto">
                            <source src="/media/{{contents_info.upload_file}}" type="video/mp4">
                        </video>
                    </div>
                </form>
            </div>
        </section>
        <div class="section" id="section2">
            <div class="container">
                <div class="row">
                    <div class="img_box">
                        <div class="title_box" style="margin-bottom: 3rem;">
                            <h2 style="margin-left : 5px;  font-size: 50px; font-family: 'MinSans-Medium';"><strong>{{contents_info.title}}</strong></h2>

                            <span> 조회수 {{contents_info.hits}} 회 </span>
                            <span> 추천수 {{contents_info.likes}} 회 </span>

                            <div id="btn_group">
                                <span>
                                    <button id="test_btn1">
                                        <a id = "likelink" href="{% url 'display:VODLike' contents_info.id%}">좋아요</a>
                                        </button>
                                </span>
                            </div>
                        </div>

                        <div class="img">
                        {% for customUser in user_img %}
                            <img class="profile_user_img" src = "/media/{{customUser.user_profile}}" alt ="No Content">
                        {% endfor %}
                            <span style="font-size: 35px; font-family: 'MinSans-Medium'">{{contents_info.nickname}}</span>
                            {% for customUser in description_user %}
                            <p style="font-size: 25px">{{customUser.user_description}}</p>
                            {% endfor %}
                            <div class="gray-line"></div>
                            <h3 style="margin-top: 3.5rem; margin-left: 90px; margin-right: 80px; line-height: 5%; font-size: 35px; font-family: 'MinSans-Medium'">작품명</h3>
                            <p style="font-size: 25px;">{{contents_info.title}}</p>
<!--                            <div class="gray-line"></div>-->
                            <div class="detail_contents" style="margin-left: 80px; margin-right: 70px;">
                                <h4 style="margin-left: 10px; margin-right: 80px; font-size: 35px; font-family: 'MinSans-Medium'">작품소개</h4>
                                <p style="margin-left: 10px; margin-right: 10px; font-size: 25px;">{{description_info.description}}</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="section" id="section3"  >
            <h3><strong>댓글 영역 : 댓글기능은 추후 지원될 예정입니다.</strong></h3>
        </div>
    </div>


    <script type="text/javascript">

// Websocket connection - start
// 웹 서버를 접속한다.
var webSocket = new WebSocket("ws://203.250.33.53:9998");
// 웹 서버와의 통신을 주고 받은 결과를 출력할 오브젝트를 가져옵니다.
var messageTextArea = document.getElementById("messageTextArea");

// 소켓 접속이 되면 호출되는 함수
webSocket.onopen = function(message){
    console.log("MediaServer connected.. with websocket..\n");
    webSocket.send(globalVal);
};
// 소켓 접속이 끝나면 호출되는 함수
webSocket.onclose = function(message){
    console.log("MediaServer Disconnect...\n");
};
// 소켓 통신 중에 에러가 발생되면 호출되는 함수
webSocket.onerror = function(message){
    console.log("error...\n");
};
// 소켓 서버로 부터 메시지가 오면 호출되는 함수.
webSocket.onmessage = function(message){
// 출력 area에 메시지를 표시한다.
    console.log("Recieve From MediaServer => "+message.data+"\n");
};

//서버 접속 끊
function disconnect(){
webSocket.close();
}

//자바스크립트에서 템플릿 태그로 그대로 로드할 시 escape 문자와 함께 출력 됨
//이를 해결하기 위해 템플릿 태그 내 | safe 옵션을 붙이지만 json 형태로 변환할 수 없음
//대신 .replace(/&#x27;/g, "\""); 통해 escape 문자 삭제 가능

//현재 json으로 옮기는 도중 모든 객체를 가진 오브젝트는 json으로 변환이 되지 않는 것을 보았다
//이는 특정 필드가 재대로 변환되지 않는다는 뜻

//오브젝트 전체
let rawdata = "{{content2server}}";
console.log("rawdata", rawdata);

// var content2server_dic = "{{content2server}}".replace(/&quot;/g, "\"");
//     console.log("content2server_dic", content2server_dic);
let content2server_dic = "{{content2server}}".replace(/&#x27;/g, "\"");
//console.log("content2server_dic", content2server_dic);

const content2server_Json = JSON.parse(content2server_dic);
// console.log("content2server_Json", content2server_Json);

// console.log("content2server_Json", content2server_Json[0]['id']);
// console.log("content2server_Json", content2server_Json[0]['title']);
// console.log("content2server_Json", content2server_Json[0]['upload_file']);

let globalVal = content2server_Json[0]['upload_file']
// console.log("미디어 서버 전송 데이터", content2server_Json["upload_file"]);
//console.log("미디어 서버 전송 데이터", globalVal);
    </script>
    </body>
</html>

cms_system/display/templates/display/picdetail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <link href="{% static './assets/css/detail.css' %}" rel="stylesheet">
        <link href="{% static './assets/css/button.css' %}" rel="stylesheet">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" type="text/css" href="https://www.w3schools.com/w3css/4/w3.css">
    </head>

    <body>
<!--    전체 레이아웃 시작-->
    <div id="wrap">
<!--    헤더-->
    <div class="container">
	 <div class="w3-top" style="margin-left: -80px; right: 0px">
             <div class="w3-bar w3-black w3-card" style="font-size: 30px;">
                 <a href="{% url 'display:signage' %}" \
                    class="w3-bar-item w3-button w3-padding-large" \
                    style="justify-content: center;">BACK</a>
                 <a href="{% url 'index' %}" \
                    class="w3-bar-item w3-button w3-padding-large w3-hide-small" \
                    style="justify-content: center;" >COMMUNITY</a>
             </div>
	</div>

        <article class="no-pd" id="content" > </article>
        <div class="headerBlock"></div>
        <section id="section1" style="margin-top: 69px;">
            <div class="container">
                <p></p>
                <form method="POST" enctype="multipart/form-data"> <!-- 왜 form 태그가 있는거지? -->
                    {% csrf_token %}
                    <div id="div1">
                        <img id="picture"  style="height: 400px; width: 100%; object-fit: cover;"
                             src = "/media/{{contents_info.upload_file}}" alt="NO Content">
                    </div>
                </form>
            </div>
        </section>
        <div class="section" id="section2">
            <div class="container">
                <div class="row">
                    <div class="img_box">
                        <div class="title_box" style="margin-bottom: 3rem;">
                            <h2 style="margin-left : 5px;  font-size: 50px; font-family: 'MinSans-Medium';"><strong>{{contents_info.title}}</strong></h2>

                            <span> 조회수 {{contents_info.hits}} 회 </span>
                            <span> 추천수 {{contents_info.likes}} 회 </span>

                            <div id="btn_group">
                                <span>
                                    <button id="test_btn1">
                                        <a id = "likelink" href="{% url 'display:ContentLike' contents_info.id%}">좋아요</a>
                                        </button>
                                </span>
                            </div>
                        </div>

                        <div class="img">
                        {% for customUser in user_img %}
                            <img class="profile_user_img" src = "/media/{{customUser.user_profile}}" alt ="No Content">
                        {% endfor %}
                            <span style="font-size: 35px; font-family: 'MinSans-Medium'">{{contents_info.nickname}}</span>
                            {% for customUser in description_user %}
                            <p style="font-size: 25px; word-wrap:break-word; ">{{customUser.user_description}}</p>
                            {% endfor %}
                            <div class="gray-line"></div>
                            <h3 style="margin-top: 3.5rem; margin-left: 90px; margin-right: 80px; line-height: 5%; font-size: 35px; font-family: 'MinSans-Medium'">작품명</h3>
                            <p style="font-size: 25px;">{{contents_info.title}}</p>

                            <div class="detail_contents" style="margin-left: 80px; margin-right: 70px;">
                                <h4 style="margin-left: 10px; margin-right: 80px; font-size: 35px; font-family: 'MinSans-Medium'">작품소개</h4>
                                <p style="margin-left: 10px; margin-right: 10px; font-size: 25px;">{{description_info.description}}</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="section" id="section3"  >
            <h3><strong>댓글 영역 : 댓글기능은 추후 지원될 예정입니다.</strong></h3>
        </div>
    </div>

    <script type="text/javascript">

// Websocket connection - start
// 웹 서버를 접속한다.
var webSocket = new WebSocket("ws://203.250.33.53:9998");
// 웹 서버와의 통신을 주고 받은 결과를 출력할 오브젝트를 가져옵니다.
var messageTextArea = document.getElementById("messageTextArea");

// 소켓 접속이 되면 호출되는 함수
webSocket.onopen = function(message){
    console.log("MediaServer connected.. with websocket..\n");
    webSocket.send(globalVal);
};
// 소켓 접속이 끝나면 호출되는 함수
webSocket.onclose = function(message){
    console.log("MediaServer Disconnect...\n");
};
// 소켓 통신 중에 에러가 발생되면 호출되는 함수
webSocket.onerror = function(message){
    console.log("error...\n");
};
// 소켓 서버로 부터 메시지가 오면 호출되는 함수.
webSocket.onmessage = function(message){
// 출력 area에 메시지를 표시한다.
    console.log("Recieve From MediaServer => "+message.data+"\n");
};

//서버 접속 끊
function disconnect(){
webSocket.close();
}

//자바스크립트에서 템플릿 태그로 그대로 로드할 시 escape 문자와 함께 출력 됨
//이를 해결하기 위해 템플릿 태그 내 | safe 옵션을 붙이지만 json 형태로 변환할 수 없음
//대신 .replace(/&#x27;/g, "\""); 통해 escape 문자 삭제 가능

//현재 json으로 옮기는 도중 모든 객체를 가진 오브젝트는 json으로 변환이 되지 않는 것을 보았다
//이는 특정 필드가 재대로 변환되지 않는다는 뜻

//오브젝트 전체
let rawdata = "{{content2server}}";
console.log("rawdata", rawdata);

// var content2server_dic = "{{content2server}}".replace(/&quot;/g, "\"");
//     console.log("content2server_dic", content2server_dic);
let content2server_dic = "{{content2server}}".replace(/&#x27;/g, "\"");
//console.log("content2server_dic", content2server_dic);

const content2server_Json = JSON.parse(content2server_dic);
// console.log("content2server_Json", content2server_Json);

// console.log("content2server_Json", content2server_Json[0]['id']);
// console.log("content2server_Json", content2server_Json[0]['title']);
// console.log("content2server_Json", content2server_Json[0]['upload_file']);

let globalVal = content2server_Json[0]['upload_file']
// console.log("미디어 서버 전송 데이터", content2server_Json["upload_file"]);
//console.log("미디어 서버 전송 데이터", globalVal);
    </script>
    </body>
</html>

cms_system/display/templates/display/projectorShow.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
        변경하지 않는 구역입니다.
    </div>

    <div>변경해야하되는 구역<div>
    <img src = "/media/contents/UID-1/v1.jpg">
    <div>변경해야하되는 구역<div>

    {% for content in projector_content %}
    <p>test {{content}}</p>

        <img src= "/media/{{content.upload_file}}"
             alt="No Content"
             style="width:10%; height:10%; cursor:pointer"
             class="w3-hover-opacity contents">
    {%endfor%}

    <script type="text/javascript">

        //오브젝트 전체
        let contents_list_dic = "{{projector_content}}".replace(/&gt;/g, "\"");
        let contents_list_dic2 = contents_list_dic.replace(/&lt;/g, "\"");
        console.log("contents_list_dic2", contents_list_dic2);

    </script>
</body>
</html>