cms_system/cms_system/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),

    path('admin/', admin.site.urls),

    path('polls/', include('polls.urls')),
    path('user/', include('user.urls')),
    path('contents/', include('contents.urls')),
    path('display/', include('display.urls')),

    # 김보
    path('community/', include('community.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cms_system/contents/urls.py
from . import views
from django.urls import path

app_name = "contents"
urlpatterns = [
    path('', views.contents, name='contents'),
    path('upload/', views.UploadView, name="upload"),
    path('dashboard/', views.DashboardView, name="dashboard"),
    path('update/<int:id>', views.UpdateView, name="update"),
    path('delete/<int:id>', views.DeleteView, name="delete"),
]

cms_system/user/urls.py
#-*- coding: utf-8 -*-

from . import views
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.just, name='just'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
]

cms_system/contents/models.py
from django.db import models
from tinymce.models import HTMLField
from django.conf import settings
from django.core.validators import FileExtensionValidator


def user_directory_path(instance, filename):
    print("Contents : 사용자 ID", instance.userFK.id)
    print("Contents : 콘텐츠 타입", instance.contentType)
    print("Contents : 파일명", filename)

    return 'contents/UID-{0}/{1}/{2}'.format(instance.userFK.id, instance.contentType, filename)


class Contents(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, null=True)
    createDate = models.DateTimeField(auto_now_add=True)
    lastEditDate = models.DateTimeField(auto_now=True)
    is_Accepted = models.BooleanField(default=True)
    contentType = models.CharField(max_length=3, null=True)
    hits = models.DecimalField(max_digits=11, decimal_places=0, default=0, null=True)   # 조회수
    likes = models.DecimalField(max_digits=11, decimal_places=0, default=0, null=True)   # 좋아요수

    # 특정 확장자만 허용
    # https://sundries-in-myidea.tistory.com/85
    # 메인화면으로 REDIRECT는 함, db에 저장되지않음, 확장자 검사는 HTML에서해야할 듯
    upload_file = models.FileField(null=True, upload_to=user_directory_path, blank=True, validators=[
        FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4'])])

    theme_id = models.ForeignKey("Theme", related_name="contents", on_delete=models.CASCADE, db_column="theme_id",
                                 null=True, blank=True)

    userFK = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, db_column="userFK", null=False)

    def __str__(self):
        return self.title


class Contents_Description(models.Model):
    id = models.AutoField(primary_key=True)
    description = HTMLField()
    width = models.CharField(max_length=10, null=True)
    height = models.CharField(max_length=10, null=True)
    HVType = models.CharField(max_length=10, null=True)  # 가로형 세로형 horizontal, vertical
    thumbnailPath = models.CharField(max_length=200, null=True)
    contentFK = models.ForeignKey(Contents, on_delete=models.CASCADE, db_column="contentsFK", null=True, blank=True)


class Theme(models.Model):
    # CHOICE = (('문화/관광', '문화/관광'), ('스포츠/레저', '스포츠/레저'), ('공예', '공예'), ('연예', '연예'), ('놀이','놀이'))

    id = models.AutoField(primary_key=True)
    # themeValue = models.CharField(max_length=100, choices=CHOICE, null=True, default="")
    themeValue = models.CharField(max_length=100, null=True, default="")

    def __str__(self):
        return self.themeValue


class Detail_Theme(models.Model):
    id = models.AutoField(primary_key=True)
    content = models.CharField(max_length=100, null=False)
    theme_id = models.ForeignKey("Theme", related_name="Detail_Theme", on_delete=models.CASCADE, db_column="theme_id")


class Content_Like(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateTimeField(auto_now_add=True)
    contents_id = models.ForeignKey("Contents", related_name="Content_Like", on_delete=models.CASCADE,
                                    db_column="contents_id")
    userFK = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, db_column="userFK", null=False)


class Content_Comment(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateTimeField(auto_now_add=True)
    contents_id = models.ForeignKey("Contents", related_name="Content_Comment", on_delete=models.CASCADE,
                                    db_column="contents_id")
    userFK = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, db_column="userFK", null=False)

cms_system/contents/forms.py
from django import forms
from .models import Contents, Contents_Description, Theme

class ContentsUploadForm(forms.ModelForm):
    class Meta:
        model = Contents
        fields = ['title', 'upload_file']

class ContentsDescriptionForm(forms.ModelForm):
    class Meta:
        model = Contents_Description
        fields = ['description']

class SelectThemeForm(forms.ModelForm):
    class Meta:
        model = Theme
        fields = ['themeValue']

    def __init__(self, *args, **kwargs):
        super(SelectThemeForm, self).__init__(*args, **kwargs)
        self.fields['themeValue'].queryset = Theme.objects.all().values_list('themeValue', flat=True).order_by('id')

cms_system/contents/views.py
from django.shortcuts import render, redirect
from .forms import ContentsUploadForm, ContentsDescriptionForm
from .models import Contents, Contents_Description, Theme
from django.db.models import Q
from .files import *
from .mediaProcessing import *
from django.contrib.auth.models import User
import os

def contents(request):
    print(request.user.id)

    return render(request, 'contents/contents.html')

def UploadView(request):
    print("contents/views/UploadView")
    print("현재 계정 {0} 현재 계정 ID {1}".format(request.user, request.user.id))

    theme_list = Theme.objects.all()

    if request.method == 'POST':
        contentsUploadForm = ContentsUploadForm(request.POST, request.FILES)
        contentsDescriptionForm = ContentsDescriptionForm(request.POST)

        if contentsUploadForm.is_valid() and contentsDescriptionForm.is_valid():

            file = (str(contentsUploadForm.cleaned_data['upload_file']))
            filename, fileType = FileTypeCheck(file)


            request_theme = request.POST['Theme']
            # theme_id = Theme.objects.get(themeValue=request_theme).id
            theme_obj = Theme.objects.get(themeValue=request_theme)

            contents = contentsUploadForm.save(commit=False)
            contents.userFK = request.user
            contents.contentType = fileType
            contents.theme_id = theme_obj
            contents.save()

            description = contentsDescriptionForm.save(commit=False)
            current_content = Contents.objects.filter(Q(userFK=request.user)).latest('id')
            print("오잉?", current_content)
            description.contentFK = current_content


            BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            BASE_PATH = "{0}/media/contents/UID-{1}/{2}".format( \
                BASE_DIR, request.user.id, fileType)

            if fileType == "IMG":

                FILE_DIR = "{0}/vod-{1}/".format(BASE_PATH, filename)
                IMG_PATH = "{0}/{1}".format(BASE_PATH, file)
                VOD_PATH = "{0}/vod-{1}/{2}.mp4".format(BASE_PATH, filename, filename)
                TS_PATH = "{0}/vod-{1}/clip_%04d.ts".format(BASE_PATH, filename)
                M3U8_PATH = "{0}/vod-{1}/{2}.m3u8".format(BASE_PATH, filename, filename)

                createDirectory(FILE_DIR)
                vodConvert = img2video(IMG_PATH, VOD_PATH)
                video2m3u8(VOD_PATH, TS_PATH, M3U8_PATH, vodConvert)

                fileInfo = GetFileInfo(IMG_PATH, fileType)
                description.width = fileInfo['width']
                description.height = fileInfo['height']
                description.HVType = fileInfo['HVType']
                description.save()

            else:  # VOD

                FILE_DIR = "{0}/vod-{1}/".format(BASE_PATH, filename)
                VOD_PATH = "{0}/{1}.mp4".format(BASE_PATH, filename)
                TS_PATH = "{0}/vod-{1}/clip_%04d.ts".format(BASE_PATH, filename)
                M3U8_PATH = "{0}/vod-{1}/{2}.m3u8".format(BASE_PATH, filename, filename)
                THUMBNAIL_PATH = "{0}/thumbnail-{1}/".format(BASE_PATH, filename)
                print("THUMBNAIL_PATH", THUMBNAIL_PATH)
                createDirectory(FILE_DIR)
                video2m3u8(VOD_PATH, TS_PATH, M3U8_PATH, 0)

                fileInfo = GetFileInfo(VOD_PATH, fileType)
                description.width = fileInfo['width']
                description.height = fileInfo['height']
                description.HVType = fileInfo['HVType']
                description.thumbnailPath = CutFilePath(THUMBNAIL_PATH, "media/")
                description.save()

                # 비디오 프레임 추출
                DIR = createDirectory(THUMBNAIL_PATH)
                print("여기다", DIR) # DIR + thumnail.jpg
                print("비디오 위치", VOD_PATH)
                GetThumbnail(VOD_PATH, DIR)



        return redirect('/')
    else:
        contentsUploadForm = ContentsUploadForm()
        contentsDescriptionForm = ContentsDescriptionForm()

        context = {
            'contentsUploadForm': contentsUploadForm,
            'contentsDescriptionForm': contentsDescriptionForm,
            'theme_list': theme_list
        }
        return render(request, 'contents/contents_Upload.html', context)

# UpdateView
def UpdateView(request, id):
    print("You are in ContentUpdate, Contents ID is %d " % id)

    contents = Contents.objects.get(id=id)
    description = Contents_Description.objects.get(contentFK=contents)
    theme_list = Theme.objects.all()

    c = Contents.objects.filter(id=id).values("theme_id")
    contents_in_theme = Theme.objects.get(id__in=c)
    contents_in_themeValue = contents_in_theme.themeValue

    if request.method == 'POST':
        contentsUploadForm = ContentsUploadForm(request.POST, request.FILES)
        contentsDescriptionForm = ContentsDescriptionForm(request.POST)

        if contentsUploadForm.is_valid() and contentsDescriptionForm.is_valid():

            request_theme = request.POST['Theme']
            # theme_id = Theme.objects.get(themeValue=request_theme).id
            theme_obj = Theme.objects.get(themeValue=request_theme)

            contents.title = contentsUploadForm.cleaned_data['title']
            contents.contentType = contentsUploadForm.cleaned_data['contentType']
            contents.upload_file = contentsUploadForm.cleaned_data['upload_file']
            contents.userFK = request.user
            contents.theme_id = theme_obj
            contents.save()

            description.description = contentsDescriptionForm.cleaned_data['description']
            description.save()

        return redirect('/')
    else:
        contentsUploadForm = ContentsUploadForm()
        contentsDescriptionForm = ContentsDescriptionForm()

        context = {
            'contentsUploadForm': contentsUploadForm,
            'contentsDescriptionForm': contentsDescriptionForm,
            "contents_info": contents,
            "description_info": description,
            'theme_list': theme_list,
            'contents_in_themeValue': contents_in_themeValue
        }

    return render(request, 'contents/contents_update.html', context)

def DashboardView(request):
    print("You are in ContentDashboard")

    # 현재 사용자 ID 가지고 오기
    current_user = request.user
    current_user_id = User.objects.get(username=current_user).id
    # print("contentsID : ", current_user_id)

    # 업로드한 객체에서 사용자의 ID를 가지는 객체만 추리기
    # 해당 객체의 파일 경로 가지고 오기
    # get()는 1개의 객체, 여러개의 객체는 filter() 사용
    # value('필드명') : 해당 필드에 대해서만 추출

    contents = Contents.objects.filter(userFK=current_user_id).values('id', 'title', 'upload_file')

    context = {"contents_list": contents}
    return render(request, 'contents/contents_dashboard.html', context)


def DeleteView(request, id):

    print("You are in ContentDelete, Contents ID is %d " % id)
    print("delete!!")
    content = Contents.objects.get(id=id)
    content.delete()
    return redirect('/contents/dashboard/')

def HideView(request, id):
    pass

cms_system/contents/templates/contents/base.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

cms_system/contents/templates/contents/contents.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
hidfj;sldfjdslkfjdlsfsdfsd
</body>
</html>

cms_system/contents/templates/contents/contents_Upload.html
{% block content %}

<h1>contents</h1>

<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>콘텐츠 이름 : {{contentsUploadForm.title}}</p>
        <!-- contents type 사용자 입력 삭제-->
        <p>콘텐츠 업로드 : {{contentsUploadForm.upload_file}}</p>
        <p>콘텐츠 소개글 : {{contentsDescriptionForm.description}}</p>

        <p><select name = "Theme">
            <option disabled = "True" selected>콘텐츠 테마 선택</option>
            {% for theme in theme_list %}
            <option>{{theme.themeValue}}</option>
            {% endfor %}
        </select></p>

        <input type="submit" class="btn btn-primary col-12" value="Submit">
    </form>
</div>
{% endblock %}

cms_system/contents/templates/contents/contents_dashboard.html
{% block content %}

<!DOCTYPE html>
{% load static %}

<html lang="en">
	<head>
		<title>Mediumish - A Medium style template by WowThemes.net</title>

		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">

		<link rel="icon" href="assets/img/favicon.ico">

		<!-- Bootstrap core CSS -->
		<link href="{% static './assets/css/bootstrap.min.css' %}" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="https://www.w3schools.com/w3css/4/w3.css">

		<!-- Fonts -->
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">

		<!-- Custom styles for this template -->
		<link href="{% static './assets/css/mediumish.css' %}" rel="stylesheet">
	</head>
<body>

<div class="container">
	 <div class="w3-top" style="margin-left: -80px; right:0px;">
             <div class="w3-bar w3-black w3-card">
                 <a href="/" class="w3-bar-item w3-button w3-large  w3-hide-small w3-right w3-black"><i class="fa fa-home"></i></a>
                 <a href="." class="w3-bar-item w3-button w3-padding-large" style="justify-content: center;">DASHBOARD</a>
                 <a href="{% url 'contents:upload' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-center" style="justify-content: center;" >UPLOAD</a>
             </div>
	</div>

<!-- Begin Site Title
================================================== -->
<div class="container">
	<div class="mainheading">
		<h1 class="sitetitle">DashBoard</h1>
		<p class="lead">
<!--            글씨적어도됨 -->
		</p>
	</div>
<!-- End Site Title
================================================== -->

	<!-- Begin Featured
	================================================== -->
	<section class="featured-posts">
	<div class="section-title">
		<h2><span>All Works</span></h2>
	</div>
	<div class="card-columns listfeaturedtag">
{% for content in contents_list %}
		<!-- begin post -->
		<div class="card">
			<div class="row">
				<div class="col-md-5 wrapthumbnail">
					<a href="post.html">

                        <div class="thumbnail" style="background-image:url(/media/{{content.upload_file}}); margin-top:-2px;"></div>
					</a>
				</div>
				<div class="col-md-7">
					<div class="card-block">
						<h2 class="card-title" style="margin-top: 30px;font-size: 20px; font-family: 'MinSans-Medium';">{{content.title}}</h2>

						<div class="metafooter">
							<div class="wrapfooter">
								<span class="meta-footer-thumb"></span>
								<span class="author-meta">
								<span class="post-name"></span><br/>
                                    <span class="post-read">
                                        <a class="a1" style="font-size: 20px; font-family: 'MinSans-Medium'" href="{% url 'contents:update' content.id %}"> 수정 </a>
									<a class="a2" style="font-size: 20px; font-family: 'MinSans-Medium'; font-family: 'MinSans-Medium'" href="{% url 'contents:delete' content.id %}"> 삭제 </a>
                                    </span>
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- end post -->
        {%endfor%}
	</div>
	</section>
	<!-- End Featured
	================================================== -->

	<!-- Begin Footer
	================================================== -->
	<div class="footer">
		<p class="pull-left">
			 Copyright &copy; 2022 CMS
		</p>
		<p class="pull-right">
			 Mediumish Theme by <a target="_blank" href="https://www.wowthemes.net">WowThemes.net</a>
		</p>
		<div class="clearfix">
		</div>
	</div>
	<!-- End Footer
	================================================== -->

</div>
<!-- /.container -->

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/contents/static/assets/js/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="/contents/static/assets/js/bootstrap.min.js"></script>
<script src="/contents/static/assets/js/ie10-viewport-bug-workaround.js"></script>
</div>
</body>
</html>
{% endblock %}

cms_system/contents/templates/contents/contents_update.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="assets/img/favicon.ico">
<title>Mediumish - A Medium style template by WowThemes.net</title>
<!-- Bootstrap core CSS -->
<link href="{% static './assets/css/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://www.w3schools.com/w3css/4/w3.css">
<!-- Fonts -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static './assets/css/mediumish.css' %}" rel="stylesheet">
<!--	<link href="/contents/static/assets/css/mediumish.css" rel="stylesheet">-->
</head>
<body>

<!-- Begin Nav
================================================== -->
<!--<nav class="navbar navbar-toggleable-md navbar-light bg-white fixed-top mediumnavigation">-->
<!--<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">-->
<!--<span class="navbar-toggler-icon"></span>-->
<!--</button>-->
<div class="container">
	 <div class="w3-top" style="margin-left: -80px; right: 0px">
             <div class="w3-bar w3-black w3-card">
                 <a href="{% url 'contents:dashboard' %}" class="w3-bar-item w3-button w3-padding-large" style="justify-content: center;">DASHBOARD</a>
                 <a href="{% url 'index' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small" style="justify-content: center;" >COMMUNITY</a>
             </div>
	</div>
<!--</div>-->
<!--</nav>-->
<!-- End Nav
================================================== -->

<!-- Begin Site Title
================================================== -->
<div class="container" >
	<div class="mainheading">
		<h1 class="sitetitle">EDIT</h1>
		<p class="lead">
<!--            글씨적어도됨 -->
		</p>
	</div>
<!-- End Site Title
================================================== -->

	<!-- Begin Featured
	================================================== -->
	<section class="featured-posts">
        <div class="section-title">
		<h2><span>{{contents_info.title}}</span></h2>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="basic_inform">
            <p>콘텐츠 번호 : {{contents_info.id}}</p>
            <hr>
            <p>등록 일자 : {{contents_info.createDate}}</p>
            <p>수정 일자 : {{contents_info.lastEditDate}}</p>
            </div>
            <hr>
            <p>콘텐츠 제목 : {{contents_info.title}}</p>
            <p>콘텐츠 제목 변경 : {{contentsUploadForm.title}}</p>
            <hr>
            <p>콘텐츠 저작자 : {{contents_info.userFK_id}}</p>
            <hr>
            <p>콘텐츠 테마 : {{contents_in_themeValue}}</p>
            <p>콘텐츠 테마 변경
                <select name = "Theme">
                <option disabled = "True" selected>콘텐츠 테마 선택</option>
                {% for theme in theme_list %}
                <option>{{theme.themeValue}}</option>
                {% endfor %}
            </select></p>
            <hr>
            <p>콘텐츠 타입 : {{contents_info.contentType}}</p>
            <p>콘텐츠 타입 변경 : {{contentsUploadForm.contentType}}</p>
            <hr>
            <p>심사 여부 : {{contents_info.is_Accepted}}</p>
            <hr>
            <p>현재 콘텐츠 파일명 : {{contents_info.upload_file}}</p>
                <p>콘텐츠 파일 변경 : </p>
            <div class="img_box" style="text-align: left">
            <img width="30%" height="20%" src = "/media/{{contents_info.upload_file}}" alt="NO Content">
                </div>
                 <p class="btn btn-primary col-12" style="top: 10px; border-radius: 10px;cursor: pointer;">{{contentsUploadForm.upload_file}}</p>
            <hr>
            <p>콘텐츠 소개글 : {{description_info.description}}</p>
            <p>콘텐츠 소개글 변경 : {{contentsDescriptionForm.description}}</p>
            <hr>
            <p>등록 일자 : {{contents_info.createDate}}</p>
            <hr>
            <p>수정 일자 : {{contents_info.lastEditDate}}</p>
               <br>
                <div class="back_submit_choice_container" style="float: right">
                    <input type="submit" class="btn btn-primary col-12" style="cursor: pointer; border-radius: 10px; width: 60px; bottom: 10px;" value="변경">
                    <a class="btn btn-primary col-12" style="border-radius: 10px; width: 60px; bottom: 10px;" href="{% url 'contents:dashboard' %}">취소</a>
                </div>
        </form>


	</section>
	<!-- End List Posts
	================================================== -->

	<!-- Begin Footer
	================================================== -->
	<div class="footer">
		<p class="pull-left">
			 Copyright &copy; 2022 CMS
		</p>
		<p class="pull-right">
			 Mediumish Theme by <a target="_blank" href="https://www.wowthemes.net">WowThemes.net</a>
		</p>
		<div class="clearfix">
		</div>
	</div>
	<!-- End Footer
	================================================== -->

</div>
<!-- /.container -->

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!--<script src="/contents/static/assets/js/jquery.min.js"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<!--<script src="/contents/static/assets/js/bootstrap.min.js"></script>-->
<!--<script> src="{% static './assets/js/ie10-viewport-bug-workaround.js' %}"></script> -->
<!--<script src="/contents/static/assets/js/ie10-viewport-bug-workaround.js"></script>-->
<script src="{% static './assets/js/ie10-viewport-bug-workaround.js' %}"></script>
<script src="{% static './assets/js/bootstrap.min.js' %}"></script>
<script src="{% static './assets/js/jquery.min.js' %}"></script>
</div>
</body>
</html>