cms_system/cms_system/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),

    path('admin/', admin.site.urls),

    path('polls/', include('polls.urls')),
    path('user/', include('user.urls')),
    path('contents/', include('contents.urls')),
    path('display/', include('display.urls')),

    # 김보
    path('community/', include('community.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cms_system/user/urls.py
#-*- coding: utf-8 -*-

from . import views
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.just, name='just'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
]

cms_system/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

def profile_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    print("user : 사용자 ID", instance.user.id)
    print("user : 파일명", filename)

    return 'Profile/UID-{0}/{1}'.format(instance.user.id, filename)

SYSTEM_AUTHORITY = (
        ('SUPER_ADMIN', 'Super_Admin'),
        ('SHELTER_ADMIN', 'Shelter_Admin'),
        ('CONTENTS_CREATOR', 'Contents_CREATOR'),
        ('USER', 'User'),
    )

class CustomUser(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, default=0)
    nickname = models.CharField(max_length=50, null=True, default="CMS USER")
    user_description = models.TextField(max_length=500, blank=True, null=True, default=0)
    user_profile = models.FileField(null=True, upload_to=profile_directory_path, blank=True, \
                                    validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])
    user_auth = models.CharField(max_length=200, choices=SYSTEM_AUTHORITY, null=True, default=0)

    # def __str__(self):
    #     return self.user.username

    def __str__(self):
        return self.nickname

cms_system/user/forms.py
from .models import CustomUser
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm

class UserSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)

        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user

class UserAdditionalSignUpForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['nickname', 'user_description', 'user_auth', 'user_profile']

cms_system/user/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth import authenticate
from .forms import UserAdditionalSignUpForm, UserSignUpForm

# 회원 가입
def just(request):
    print("just")

    return render(request, 'user/justpage.html')

def signup(request):
    if request.method == 'POST':

        form = UserSignUpForm(request.POST)
        additional_form = UserAdditionalSignUpForm(request.POST, request.FILES)


        if form.is_valid() and additional_form.is_valid():

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')

            user = form.save()

            customuser = additional_form.save(commit=False) # 지금 저장하지 않겠다.
            customuser.user = user
            customuser.save()

            user = authenticate(username=username, password=password)
            auth.login(request, user)

            return redirect('/')
    else:
        form = UserSignUpForm()
        additional_form = UserAdditionalSignUpForm()

    context = {'form': form, 'additional_form': additional_form}
    return render(request, 'user/signup.html', context)

# 로그인
def login(request):
    # login으로 POST 요청이 들어왔을 때, 로그인 절차를 밟는다.
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']

        # 해당 username과 password와 일치하는 user 객체를 가져온다.
        user = auth.authenticate(request, username=username, password=password)

        # 해당 user 객체가 존재한다면
        if user is not None:
            # 로그인, 현재 계정 명 확인
            auth.login(request, user)

            print("login success")
            print("current user " + str(user))
            return redirect('/')        # 203.250.33.53 으로 직행
    # 존재하지 않는다면
        else:
            # 딕셔너리에 에러메세지를 전달하고 다시 login.html 화면으로 돌아간다.
            error_msg = 'username or password is incorrect.'
            return render(request, 'user/login.html', {'error': error_msg})

    # login으로 GET 요청이 들어왔을때, 로그인 화면을 띄워준다.
    else:
        return render(request, 'user/login.html')


# 로그 아웃
def logout(request):
    # logout으로 POST 요청이 들어왔을 때, 로그아웃 절차를 밟는다.
    if request.method == 'POST':
        auth.logout(request)
        return redirect('/')

    # logout으로 GET 요청이 들어왔을 때, 로그인 화면을 띄워준다.
    auth.logout(request)
    return redirect('/')

cms_system/user/templates/user/justpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 justpage
</body>
</html>

cms_system/user/templates/user/login.html
{#<!DOCTYPE html>#}
{#{% load static %}#}
{#<html lang="en">#}
{#<head>#}
{#     <link href="{% static './assets/css/mediumish.css' %}" rel="stylesheet">#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#{% block content %}#}
{##}
{#    <div class="container">#}
{##}
{##}
{#        <form method="POST" action="{% url 'user:login' %}">#}
{#            {% csrf_token %}#}
{#            <p>username</p>#}
{#            <input type="text" name="username">#}
{#            <br>#}
{#            <p>password</p>#}
{#            <input type="text" name="password">#}
{#            <br>#}
{#            <input type="submit" value="로그인">#}
{#</form>#}
{#    </div>#}
{#{% endblock %}#}
{#</body>#}
{#</html>#}

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="assets/img/favicon.ico">
<title>Mediumish - A Medium style template by WowThemes.net</title>
<!-- Bootstrap core CSS -->
<link href="{% static './assets/css/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://www.w3schools.com/w3css/4/w3.css">
<!-- Fonts -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static './assets/css/mediumish.css' %}" rel="stylesheet">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<!--	<link href="/contents/static/assets/css/mediumish.css" rel="stylesheet">-->
</head>
<body>

<!-- Begin Nav
================================================== -->
<!--<nav class="navbar navbar-toggleable-md navbar-light bg-white fixed-top mediumnavigation">-->
<!--<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">-->
<!--<span class="navbar-toggler-icon"></span>-->
<!--</button>-->
<div class="container">
	 <div class="w3-top" style="margin-left: -80px; right: 0px; ">
             <div class="w3-bar w3-black w3-card">
                 <a href="#" class="w3-bar-item w3-button w3-large  w3-hide-small w3-right w3-black"><i class="fa fa-home"></i></a>
                 <a href="{% url 'user:signup' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-right" style="justify-content: center;">SIGNUP</a>
             </div>
	</div>
<!--</div>-->
<!--</nav>-->
<!-- End Nav
================================================== -->

<!-- Begin Site Title
================================================== -->
<div class="container" >
	<div class="mainheading">
		<h1 class="sitetitle">Login</h1>
		<p class="lead">
<!--            글씨적어도됨 -->
		</p>
	</div>
<!-- End Site Title
================================================== -->

	<!-- Begin Featured
	================================================== -->
    <section class="featured-posts">
        <div class="section-title">
		<h2><span></span></h2>
        </div>
	<section class="containerbox">
              <form method="POST" action="{% url 'user:login' %}">
            {% csrf_token %}
            <p>아이디</p>
            <input type="text" name="username">
            <br>
              <br>
            <p>패스워드</p>
            <input type="text" name="password">
            <br>
                  <br>
{#                    <input type="submit" value="로그인">#}
{#            <input type="submit" value="로그인" class="btn btn-primary col-12" style="border-radius: 10px">#}
                  <div class="back_submit_choice_container" style="float: right">
                    <input type="submit" class="btn btn-primary col-12" style="cursor: pointer; border-radius: 10px; width: 70px; bottom: 10px;" value="로그인">
                    <a class="btn btn-primary col-12" style="border-radius: 10px; width: 60px; bottom: 10px;" href="/">취소</a>
                </div>
            </form>

	</section>
    </section>
	<!-- End List Posts
	================================================== -->

	<!-- Begin Footer
	================================================== -->
	<div class="footer">
		<p class="pull-left">
			 Copyright &copy; 2022 CMS
		</p>
		<p class="pull-right">
			 Mediumish Theme by <a target="_blank" href="https://www.wowthemes.net">WowThemes.net</a>
		</p>
		<div class="clearfix">
		</div>
	</div>
	<!-- End Footer
	================================================== -->

</div>
<!-- /.container -->

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!--<script src="/contents/static/assets/js/jquery.min.js"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<!--<script src="/contents/static/assets/js/bootstrap.min.js"></script>-->
<!--<script> src="{% static './assets/js/ie10-viewport-bug-workaround.js' %}"></script> -->
<!--<script src="/contents/static/assets/js/ie10-viewport-bug-workaround.js"></script>-->
<script src="{% static './assets/js/ie10-viewport-bug-workaround.js' %}"></script>
<script src="{% static './assets/js/bootstrap.min.js' %}"></script>
<script src="{% static './assets/js/jquery.min.js' %}"></script>
</div>
</body>
</html>

cms_system/user/templates/user/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

cms_system/user/templates/user/signup.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name = "viewport" content="width=device-width, initial-scale=1.0">#}
{#    <meta http-equiv="X-UA-Compatible" content = "ie=edge">#}
{#    <title>SignUP2</title>#}
{#</head>#}
{#<body>#}
{##}
{#    <form method="POST" enctype="multipart/form-data" action="{% url 'user:signup' %}">#}
{#        {% csrf_token %}#}
{#        {{form.as_p}}#}
{#        <p>CMS 닉네임 : {{additional_form.nickname}}</p>#}
{#        <p>내소개 : {{additional_form.user_description}}</p>#}
{#        <!-- 관리자 권한으로 변경 예정 -->#}
{#        <p>사용자 권한 : {{additional_form.user_auth}}</p>#}
{#        <p>내 프로필 이미지 : {{additional_form.user_profile}}</p>#}
{##}
{#        <input type="submit" value="회원가입">#}
{#    </form>#}
{##}
{#</body>#}
{#</html>#}

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="assets/img/favicon.ico">
<title>Mediumish - A Medium style template by WowThemes.net</title>
<!-- Bootstrap core CSS -->
<link href="{% static './assets/css/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://www.w3schools.com/w3css/4/w3.css">
<!-- Fonts -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<!-- Custom styles for this template -->
<link href="{% static './assets/css/mediumish.css' %}" rel="stylesheet">
<!--	<link href="/contents/static/assets/css/mediumish.css" rel="stylesheet">-->
</head>
<body>

<!-- Begin Nav
================================================== -->
<!--<nav class="navbar navbar-toggleable-md navbar-light bg-white fixed-top mediumnavigation">-->
<!--<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">-->
<!--<span class="navbar-toggler-icon"></span>-->
<!--</button>-->
<div class="container">
	 <div class="w3-top" style="margin-left: -80px; right: 0px">
             <div class="w3-bar w3-black w3-card">
                 <a href="#" class="w3-bar-item w3-button w3-large  w3-hide-small w3-right w3-black"><i class="fa fa-home"></i></a>
                 <a href="{% url 'user:login' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-right" style="justify-content: center;" >LOGIN</a>
             </div>
	</div>
<!--</div>-->
<!--</nav>-->
<!-- End Nav
================================================== -->

<!-- Begin Site Title
================================================== -->
<div class="container" >
	<div class="mainheading">
		<h1 class="sitetitle">SignUp</h1>
		<p class="lead">
<!--            글씨적어도됨 -->
		</p>
	</div>
<!-- End Site Title
================================================== -->

	<!-- Begin Featured
	================================================== -->
    <section class="featured-posts">
        <div class="section-title">
		<h2><span>회원가입</span></h2>
        </div>
        <div class="center_box">
	<form method="POST" enctype="multipart/form-data" action="{% url 'user:signup' %}">
        {% csrf_token %}
        {{form.as_p}}
        <p>내 별명 : {{additional_form.nickname}}</p>
        <p>내 소개말 : {{additional_form.user_description}}</p>
        <!-- 관리자 권한으로 변경 예정 -->
        <p>사용자 권한 : {{additional_form.user_auth}}</p>
        <p>내 프로필 이미지 : {{additional_form.user_profile}}</p>
        <br>
        <div class="back_submit_choice_container" style="float: right">
            <input type="submit" class="btn btn-primary col-12" style="cursor: pointer; border-radius: 10px; width: 80px; bottom: 10px;" value="회원가입">
            <a class="btn btn-primary col-12" style="border-radius: 10px; width: 60px; bottom: 10px;" href="/">취소</a>
        </div>

        </form>
        </div>


	</section>
	<!-- End List Posts
	================================================== -->

	<!-- Begin Footer
	================================================== -->
	<div class="footer">
		<p class="pull-left">
			 Copyright &copy; 2022 CMS
		</p>
		<p class="pull-right">
			 Mediumish Theme by <a target="_blank" href="https://www.wowthemes.net">WowThemes.net</a>
		</p>
		<div class="clearfix">
		</div>
	</div>
	<!-- End Footer
	================================================== -->

</div>
<!-- /.container -->

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!--<script src="/contents/static/assets/js/jquery.min.js"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<!--<script src="/contents/static/assets/js/bootstrap.min.js"></script>-->
<!--<script> src="{% static './assets/js/ie10-viewport-bug-workaround.js' %}"></script> -->
<!--<script src="/contents/static/assets/js/ie10-viewport-bug-workaround.js"></script>-->
<script src="{% static './assets/js/ie10-viewport-bug-workaround.js' %}"></script>
<script src="{% static './assets/js/bootstrap.min.js' %}"></script>
<script src="{% static './assets/js/jquery.min.js' %}"></script>
</div>
</body>
</html>